FROM registry.access.redhat.com/ubi8/ruby-25

ENV VERSION 1.0.0

LABEL io.k8s.description="echo-server: a simple UDP server that echoes back your text" \
  io.k8s.display-name="echo-server v${VERSION}" \
  io.openshift.tags="test,qa" \
  name="echo-server" \
  architecture="x86_64" \
  maintainer="github.com/FreedomBen"

COPY . /app

WORKDIR /app

USER default
EXPOSE 4321/udp
CMD /app/udp.rb
