---
apiVersion: v1
kind: Namespace
metadata:
  name: echo-server
spec:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo-server
  name: echo-server
  namespace: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
      namespace: echo-server
    spec:
      containers:
      - image: quay.io/freedomben/echo-server:latest
        name: echo-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: BASIC_OCP_DEMO_ENV
          value: master
            #- image: quay.io/freedomben/metals:latest
            #  name: metals
            #  imagePullPolicy: Always
            #  ports:
            #  - containerPort: 8443
            #    protocol: TCP
            #  envFrom:
            #  - configMapRef:
            #      name: echo-server-certs
            #  - secretRef:
            #      name: echo-server-server-key

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo-server
  name: echo-server
  namespace: echo-server
spec:
  type: NodePort
  selector:
    app: echo-server
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30180
