---
apiVersion: v1
kind: Namespace
metadata:
  name: udp-echo-server
spec:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udp-echo-server
  name: udp-echo-server
  namespace: udp-echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udp-echo-server
  template:
    metadata:
      labels:
        app: udp-echo-server
      namespace: udp-echo-server
    spec:
      containers:
      - image: quay.io/freedomben/echo-server-udp:latest
        name: udp-echo-server
        imagePullPolicy: Always
        ports:
        - containerPort: 4321
          protocol: UDP
        env:
        - name: BASIC_OCP_DEMO_ENV
          value: master

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: udp-echo-server
  name: udp-echo-server
  namespace: udp-echo-server
spec:
  type: NodePort
  selector:
    app: udp-echo-server
  ports:
  - name: 4321-udp
    port: 4321
    protocol: UDP
    targetPort: 4321
    nodePort: 30181
